### ISSUE TITLE
Natively Packaged JFX Application using HttpURLConnection Security Issue?

### ISSUE THREAD

**Issue by PeregrineFalcon** [sothawo/mapjfx#12]
I am using the caching mechanism successfully in debug mode. But once packaged in a native jfx application (OS X *.app as an example) the launcher service reports the following.

> 4/14/16 1:03:23.348 PM launchservicesd[85]: SecTaskLoadEntitlements failed error=22
4/14/16 1:03:23.350 PM launchservicesd[85]: SecTaskLoadEntitlements failed error=22
4/14/16 1:03:23.461 PM appleeventsd[55]: SecTaskLoadEntitlements failed error=22

I did some digging to see if there is a security permission necessary. Only one I could find that _may_ be of relevance is: https://docs.oracle.com/javase/8/docs/api/java/net/HttpURLConnection.html

Still trying to find more information on this but there appears to be something occurring with the Caching.
-Adam H.

**Comment by sothawo** [comment]
Hi Adam,

you say the launcher service is reporting this? Is this on application launch? Does this happen straight on starting the program or when calling the OfflineCache.setActtive(true) method?

I will build a native app using the javafx maven plugin and see if this happens there as well (OS X).

greetings
Peter

**Comment by sothawo** [comment]
Hi Adam,

I did the following, using my trakxmap application which uses mapjfx as well: I created a native app using the maven-javafx-plugin after integrating a cache setup on MapView initialization that uses a subdirectory  of _System.getProperty("java.io.tmpdir")_ as cache .

I started both the .app bundle and the app from the created dmg, both ran without problems on OS X 10.11.4, under a normal user, no administrative rights. Cache directory was filling quite alright.

With what do you build the app, what version of Java and OS X?

**Comment by PeregrineFalcon** [comment]
Upon further investigation it appears that setting a CacheDirectory in a resource folder is causing some issue when packaged using maven-javafx-plugin I will try a different directory and report back. My original suspicion appears to not be the cause of the issue.

**Comment by sothawo** [comment]
resource folder within the app package? This might be a problem, because when an app is installed, it might be with admin rights so the user running the app can't write to that directory.

Try something like `final String cacheDir = System.getProperty("java.io.tmpdir") + "/trakxmap/mapjfx-cache";`

On OSX this on my machine ends in _/var/folders/sx/gwrf8dfs3fj2kl7dxwg1ymg80000gp/T/mapjfx-cache_.

**Comment by PeregrineFalcon** [comment]
That ended up being the issue. Problem was access to the cache directory was in an inaccessible location once packaged. Thanks for the pointers.
