### ISSUE TITLE
Extent.forCoordinates() does not correctly calculate the Extent with negative longitudes

### ISSUE THREAD

**Issue by gmatrangola** [sothawo/mapjfx#14]
`maxLatitude` and `maxLongitued `are primed with `Double.MIN_VALUE` which is the smallest positive double value (very, verry tiney, but still positive). They should actually be primed with `-Double.MAX_VALUE` which will be the smallest double possible (a negative number). See: http://stackoverflow.com/questions/3884793/why-is-double-min-value-in-not-negative

**Comment by sothawo** [comment]
thanks for reporting that mistake! Fixed and deployed in 1.7.2. Should be on it's way to maven central.
