### ISSUE TITLE
Map content is not shown/rendered

### ISSUE THREAD

**Issue by breiting** [sothawo/mapjfx#22]
I just wanted to test your nice example project, however, when I am starting the demo application, I do not see any rendered OSM content (tiles) on the screen. Looks like the following:

![screen shot 2017-03-29 at 22 14 55](https://cloud.githubusercontent.com/assets/4894860/24474515/2c38ba66-14cd-11e7-997d-978a6c4a052a.png)

Here is some console output,  nothing special:

```
22:15:21.365 DEBUG [JavaFX Application Thread] com.sothawo.mapjfx.MapView - Java Version:   1.8.0_92-b14
22:15:21.365 DEBUG [JavaFX Application Thread] com.sothawo.mapjfx.MapView - JavaFX Version: 8.0.92-b14
22:15:21.366 DEBUG [JavaFX Application Thread] com.sothawo.mapjfx.MapView - OS:             Mac OS X, 10.12.3, x86_64
22:15:21.367 DEBUG [JavaFX Application Thread] com.sothawo.mapjfx.MapView - User Agent:     Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/538.19 (KHTML, like Gecko) JavaFX/8.0 Safari/538.19
22:15:21.368 DEBUG [JavaFX Application Thread] com.sothawo.mapjfx.MapView - load html into WebEngine
```

...

```
22:15:22.519 DEBUG [JavaFX Application Thread] c.s.mapjfx.MapView.JavaConnector - JS: patching anchor for https://openlayers.org/
22:15:22.520 DEBUG [JavaFX Application Thread] c.s.mapjfx.MapView.JavaConnector - JS: patching anchor for https://www.openstreetmap.org/copyright
22:15:22.521 DEBUG [JavaFX Application Thread] c.s.mapjfx.MapView.JavaConnector - JS reports zoom value 2
```

**Comment by breiting** [comment]
I used the released MVN package and the demo application in the 
https://github.com/sothawo/mapjfx-demo.git
repository

**Comment by sothawo** [comment]
While testing to answer this issue I found the same behaviour, the loading of the tiles is really slow, they load after a while, but not as it should, it seems to take up to some minutes.

In the src/main/resources directory is a mapview-local.html file which I use for development and testing, when you open this file in a browser after changing line 169 to `jsMapView.setMapType('OSM');` does it work?

I can see in three different browsers (Chrome, Firefox and Safari), that some tiles load quite noarmally, but some take a long time to load. Firefox status line shows _Übertragen der Daten von a.tile.openstreetmap.org..._

What happens if you set the map type to the _World food program admin boundaries_ and zoom out to level 7? Can you see some map outlines then? (the GIS server seems not to be available anymore, I have to remove that sample). Just to make sure the program is working and the problem is with OSM.

Another thing I found: I normally have Disconnect Desktop running tunneling my web traffic through a VPN to remove tracking. If I switch this off, the map tiles load normally, one or two take a bit longer, but no really big delays. Do you have any tools like this active that might intercept with internet traffic?

**Comment by breiting** [comment]
Thanks for the quick answer. When I am changing line 169, the web shows the correct content.
The WMS mode does work in the app and shows the boundaries. The OSM mode does only work for the html file modification, not in the demo application

**Comment by sothawo** [comment]
Ok, I did some more tests. I wrote a small JavaFX Browser application that just has a url entry field and a button to get the browser going:
`/**
 * Copyright (c) 2016 sothawo
 *
 * http://www.sothawo.com
 */
package com.sothawo.browser;

import javafx.application.Application;
import javafx.geometry.Insets;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Priority;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;
import javafx.stage.Stage;

/**
 * @author P.J. Meisch (pj.meisch@sothawo.com).
 */
public class Browser extends Application {


    /** the embedded webview. */
    private WebView webView;

    /** the engine of the embbeded webview. */
    private WebEngine webEngine;

    /** text field for entry of url. */
    private TextField urlTextField;

    // button to start loading the webpage. */
    private Button goButton;

    @Override
    public void start(Stage primaryStage) throws Exception {

        webView = new WebView();
        webEngine = webView.getEngine();

        primaryStage.setTitle("Browser");

        // create content
        BorderPane content = new BorderPane();

        // at the top url entry filed and go button
        HBox hbox = new HBox();
        hbox.setPadding(new Insets(5, 5, 5, 5));
        hbox.setSpacing(5);

        urlTextField = new TextField();
        HBox.setHgrow(urlTextField, Priority.ALWAYS);
        hbox.getChildren().add(urlTextField);

        goButton = new Button("Go");
        goButton.setOnAction(evt -> {
            webEngine.load(urlTextField.getText());
        });

        hbox.getChildren().add(goButton);

        content.setTop(hbox);

        content.setCenter(webView);

        primaryStage.setScene(new Scene(content, 1024, 800));
        primaryStage.show();
    }

}
`

When displaying my local file with this browser I have the same problems. I then checked the official OpenLayers site and found that this is not working either. The first image shows an OpenLayers sample in Chrome, the second in the small browser app:

![bildschirmfoto 2017-03-31 um 17 29 16](https://cloud.githubusercontent.com/assets/8456476/24557339/a0a2c138-1637-11e7-9080-9a119fc87b4a.png)

![bildschirmfoto 2017-03-31 um 17 29 31](https://cloud.githubusercontent.com/assets/8456476/24557361/ba07cb78-1637-11e7-83e5-772c36352862.png)

So it seems that the WebKit Browser contained in the current Java versions seems to have a problem with OSM maps. In the small browser app there is nothing customized, just the plain WebView from Java.

To be honest, at the moment I have no idea how I could fix this. Sorry I can't give you a better answer, but as WebKit is a native component, I can't even debug into the code or check what the browser is doing.

**Comment by breiting** [comment]
Thanks for your investigations. This is really a pity :-(
