### ISSUE TITLE
Custom WMS server not showing

### ISSUE THREAD

**Issue by MINDoSOFT** [sothawo/mapjfx#25]
Hello and thank you for this really useful JavaFX component!

I am trying to use an external WMS server and I add the following code to the demo application of mapjfx:

```
/** params for the fourth WMS server. */
    private WMSParam wmsParamExternalWMSServer = new WMSParam()
            .setUrl("http://ows.terrestris.de/osm/service?")
            .addParam("layers", "OpenStreetMap WMS - by terrestris")
    		.addParam("REQUEST", "GetTile");
```

And also change the line where the WMSParam is set:

```
else if (newValue == radioMsWMSWFPAdminBoundaries) {
                //mapView.setWMSParam(wmsParamWFPAdminBoundaries);
            	mapView.setWMSParam(wmsParamExternalWMSServer);
                if (oldValue == radioMsWMSGisLandsat) {
                    mapView.setMapType(MapType.OSM);
                }
                mapType = MapType.WMS;
            }          
```

This WMS server works on QGIS desktop application but in mapjfx it displays nothing.

**Comment by sothawo** [comment]
This works for me:

`        wmsParam = new WMSParam()
                .setUrl("http://ows.terrestris.de/osm/service?")
                .addParam("layers", "OSM-WMS");
`

and I have to disable local caching

**Comment by MINDoSOFT** [comment]
Yes this fixes it for me also. Thank you for your help and quick response!
