### ISSUE TITLE
Can I use a local file as a single time WMS service in mapView?

### ISSUE THREAD

**Issue by hanokhaloni** [sothawo/mapjfx#27]
Hyya,

I would like to use a silngle tile located in filesystem for use in mapjfx (for example like so : http://www.gisagmaps.com/storage/S2_download_extent.jpg?__SQUARESPACE_CACHEVERSION=1486582125381) . Is there a way to do so with current implementation of MapType.OSM ?

Thanks :)

**Comment by sothawo** [comment]
Hi,

I am on vacations, can look into this at the 21. August earliest. 

Greetings 
Peter

**Comment by sothawo** [comment]
sorry, this is not possible.
