### ISSUE TITLE
onmouseover / onmouseexit events (implementing tooltips)

### ISSUE THREAD

**Issue by skinkie** [sothawo/mapjfx#30]
I would like to show tooltips on markers etc. Will a patch be accepted adding onmouseover/exit events?

**Comment by sothawo** [comment]
sure. Do you have a pull request from a forked version or should I add you as a collaborator on this repo and you check it in in a branch?

**Comment by skinkie** [comment]
I was still evaluating options. But I'll just fork it and see if I can make it work, including an example.

**Comment by sothawo** [comment]
mouse events are in release 1.14.0; for the tooltips I'll create a new issue
