### ISSUE TITLE
Filling the area enclosed by CoordinateLine with color.

### ISSUE THREAD

**Issue by JSzut** [sothawo/mapjfx#35]
Hi,
Is it possible to fill the area enclosed with CoordinateLine with a color to get similar result?
![obraz](https://user-images.githubusercontent.com/16391563/38694957-46321e06-3e8b-11e8-8f5c-f79054ab8875.png)

**Comment by ullenboom** [comment]
Can we expect that feature soon? I think there is some demand.

**Comment by Neevel** [comment]
yes that would be really useful.

**Comment by sothawo** [comment]
thanks for bringing this back to attention; I'm quite busy at the moment, I hope to find some time for this the nexte weeks.

**Comment by sothawo** [comment]
[implemented in current release.](https://www.sothawo.com/2018/11/mapjfx-now-supports-filled-polygons/)
[description](https://www.sothawo.com/projects/mapjfx-demo/5/#polygons)
