### ISSUE TITLE
Map is generated only in top, left corner of MapView in Java SDK 9

### ISSUE THREAD

**Issue by JSzut** [sothawo/mapjfx#36]
I found out that map is generated only in top, left corner of the whole MapView after switching into Java 1.9.  In Java 1.8 works fine. How to solve it?
![obraz](https://user-images.githubusercontent.com/16391563/38700769-72120d40-3e9c-11e8-851f-c8292a8df1a5.png)

**Comment by sothawo** [comment]
I suppose this is the known problem described here: https://www.sothawo.com/2018/02/mapjfx-problems/. I had this in different versions of Java 8 and 9, can you try Java 10?

**Comment by JSzut** [comment]
I've just tried in Java 10 and problem is the same. I have even tried to create simple app just with MapView in Java SE 10, still the same:
![obraz](https://user-images.githubusercontent.com/16391563/38782653-21228c9a-40f7-11e8-8505-105b464533d5.png)

**Comment by JSzut** [comment]
Hence, looks like it is something more than Java version as it sometimes it works (@sothawo case) and sometimes not (my case).

**Comment by sothawo** [comment]
it does not always work for me, as described in the linked issue on on my web site; this seems to be a connection issue from the webkit browser to the OSM maps; but this is deep in the native calls of webkit, where I have no access to.

I have no problems whatever when I am using Bing maps, whatever flavour.

And I have this problem when just browsing the OpenLayers demo with a JavaFX application using a WebView, so this is not only with my MapView.

So the best I can recommend at the moment is to get an API key for Bing Maps (https://www.microsoft.com/en-us/maps/create-a-bing-maps-key) and try this.

**Comment by JSzut** [comment]
I've tried Bing Maps and I am even more confused as they to not work neither (I've tried both aerial and roads):
![obraz](https://user-images.githubusercontent.com/16391563/38807208-336b4ab0-417c-11e8-90a6-66006483b7d4.png)

**Comment by sothawo** [comment]
that is strange, can you share the code of your sample app, so I might try it on my machine?

**Comment by JSzut** [comment]
@sothawo I've just added to the repo with my app. I set the OSM map, but feel free to edit it for Bing maps. Please, let me know, if it works for you.

**Comment by sothawo** [comment]
![image](https://user-images.githubusercontent.com/8456476/38812868-bff4bfe6-418d-11e8-97a6-b82c1f974bb3.png)

forked it (could not clone), opened in IntelliJ and ran it using JDK 10. 

I hate unreproducible erros. So this leaves me clueless at the moment

**Comment by JSzut** [comment]
I feel the same. Will try to run on Linux and maybe few more machines. I will give you a further feedback tomorrow. Thank you for your outstanding commitment.

**Comment by JSzut** [comment]
With some delay but I'm back with quite interesting fact that map is generated properly on Linux machine. Looks like some platform-specific issue. I have to try on some other Windows.

**Comment by sothawo** [comment]
I think this might quite well be possible, as WebKit is a native implementation which is called by the Java Runtime; thanks for the hint

**Comment by JSzut** [comment]
Ok, I have just checked on different Windows machine and it works fine. Looks like my machine's WebKit problem. Do you know any way to reset/reinstall it fully?

**Comment by vewert** [comment]
Thanks for your excellent work on this project, it looks perfect for an application I am creating.
When I tried using it, however, I am noticing this same problem. It seem like the tiles do load... but verrry slowly. I tried it on Window 10 and MacOS using Java8, both with the same results.

Just as a reference, the WebView I am using WebKit 605.1 (`webView.getEngine().getUserAgent()`)

Since it seems like it might be a problem with WebKit, are there any other alternatives? I saw something about JxBrowser [https://www.teamdev.com/jxbrowser](https://www.teamdev.com/jxbrowser), but don't know anything about it, just a thought.

Thanks again for your efforts!

**Comment by sothawo** [comment]
you might want try to contact Majid Hojati ( see https://github.com/sothawo/mapjfx/issues/42#issuecomment-416639856), this is a different issue, but he wrote that he switched to jxbrowser. I do not know, if he changed mapjfx to use jxbrowser or does uses jxbrowser without mapjfx.
