### ISSUE TITLE
Issues with OfflineCache (Java 11)

### ISSUE THREAD

**Issue by ullenboom** [sothawo/mapjfx#44]
The `OfflineCache` and particular https://github.com/sothawo/mapjfx/blob/master/src/main/java/com/sothawo/mapjfx/offline/CachingURLStreamHandlerFactory.java is giving problems.

    private URLStreamHandler getURLStreamHandler(String protocol) {
        try {
            Method method = URL.class.getDeclaredMethod("getURLStreamHandler", String.class);
            method.setAccessible(true);
            return (URLStreamHandler) method.invoke(null, protocol);
        } catch (Exception e) {
            logger.warning("could not access URL.getUrlStreamHandler");
            return null;
        }
    }

The reflective call is not allowed. We are working with modules.

**Comment by sothawo** [comment]
I know. This gives a warning since Java 9. But alas the JDK does not offer a different solution to get the default URLStreamHandler - which I need for getting the data to cache - I will have to remove the caching for the version running JDK11 or later.

**Comment by vewert** [comment]
I realize this issue is closed, but I just wondering if there are any plans to implement some other kind of offline caching technique, that would be compatible with Java 11?

Thanks so much for all the work you put into this project, it is appreciated.

**Comment by sothawo** [comment]
at the moment it seems that using `--permit-illegal-access`is the only solution.
 Another possibility - might be using a different a deifferent URLStreamHandler instead of the original one. I would have to see if there a usable implementations / libraries for that.

**Comment by sothawo** [comment]
added a new issue #63
