### ISSUE TITLE
Panning map too far East or West causes invalid longitude when clicking

### ISSUE THREAD

**Issue by vewert** [sothawo/mapjfx#50]
I'm using mapjfx in a project I am working on, and I really appreciate the work you have put into this excellent project; but I have noticed a strange behaviour. If the map is zoomed out quite far, you can easily pan the world map, so that it 'wraps' around. Once you've wrapped around, when you click on the map, the longitude value returned in the `MAP_CLICKED` event, is incorrect. I was getting values like:

`"Clicked: [latitude=-31.20340495091738, longitude=-214.27734375]"`
`"Clicked: [latitude=-19.80805412808857, longitude=-335.21484375]"`

I think this also applies to `MAP_POINTER_MOVED` as well.

It looks like at the when the map wraps from one "world" to the next, going West, the longitude values re-starts at -180 and keep increasing (in the negative direction).
I was able to reproduce this, in the demo application as well. See screen shots below:

![mapjfxScreenShot1](https://user-images.githubusercontent.com/38388418/54969703-8173e900-4f3c-11e9-95eb-726ed7094454.png)
In the first screen shot I clicked on 'Normal' New Zealand, with a longitude of 175.95703125.

![mapjfxScreenShot2](https://user-images.githubusercontent.com/38388418/54969712-86389d00-4f3c-11e9-988d-048aea77fa8d.png)
In the second screen shot, I clicked on 'Wrapped' New Zealand, with a longitude of -184.39453125000

As a work-around, it looks like I could take the longitude returned from map, and if it is out of range add a multiple of 360 to it, until it is in range.

**Comment by sothawo** [comment]
Hello,

this may be indeed confusing, but is not really a fault. When zooming out, you see some areas of the world duplicated, and OpenLayers reports the ccordinates of these areas without considering the wrap around. On the one hand this is incorrect, but on the other you might need this if you want to differentiate between the two New Zealands (although I don't see a real use case).

If you need the coordinates normalized, you can use the following code (similar to what you did already):

    private Coordinate normalize(Coordinate coordinate) {
        Double longitude = coordinate.getLongitude();
        while(longitude < -180.0) longitude += 360;
        while(longitude > 180.0) longitude -= 360;
        return new Coordinate(coordinate.getLatitude(), longitude);
    }

I think I might add this normalize Method to the `Coordinate` class, but will not make an extra release, but have it contained in the next one. And I will keep it in the Java code, so the logs from Javascript will show the out-of-range values.

**Comment by vewert** [comment]
Thanks for your quick response, and for your information; that makes sense. My use cases always assume a longitude from -180 and 180, so I would use a normalized Coordinate. If you add the normalize method to your next release that would be great, otherwise I'll just create my own normalize method, and handle it on my end.

Thanks again for this excellent project!

**Comment by sothawo** [comment]
resolved; see https://www.sothawo.com/2019/03/mapjfx-2-6-0-and-1-25-0-add-support-for-normalized-coordinates/
