### ISSUE TITLE
Disable Zoom and Panning

### ISSUE THREAD

**Issue by nikki22b** [sothawo/mapjfx#51]
Hey,

is it possible to disable zooming and panning? Since the normal MapView doesn't offer these options, I don't know where to start.

**Comment by sothawo** [comment]
so basically a fixed view? Should the whole interaction with the map be disable, or should clicking be still possible? I'll have to check what is possible. And what should happen when the size of the view itself is changed?

**Comment by nikki22b** [comment]
Yes, a fixed view but Clicking the map and markers should be still possible. 

The problem with resizing the view is secondary for now. I'm developing an extra feature for a program that only runs on a certain touch-table(SUR 40) in full screen mode. Changes in view size are therefore negligible.

Thank you for Your fast Reply!

**Comment by sothawo** [comment]
https://www.sothawo.com/2019/04/mapjfx-2-7-0-and-1-26-0-add-the-possibility-to-inhibit-zoom-and-panning/
