### ISSUE TITLE
disable the browser displaying the standard context menu

### ISSUE THREAD

**Issue by sothawo** [sothawo/mapjfx#52]
the implemente dway to disable the default browser context menu on the map is not working anymore (not sure since which version). Must investigate and fix.

**Comment by myrage2000** [comment]
Hi, this would be great !
Have you looked at [setContextMenuEnabled](https://docs.oracle.com/javafx/2/api/javafx/scene/web/WebView.html#setContextMenuEnabled%28boolean%29) ?

**Comment by sothawo** [comment]
@myrage2000 I know this exists, but then this disables the contect menu on the markers and labels as well. I have Javascript code in the page which should (and used) to intercept the context menu, but this is not working anymore. Not sure when the Webkit browser changed here, because that used to work.

**Comment by trixon** [comment]
@sothawo Would it be possible to let one choose to disable the context menu for the markers too, at least for now?

Every time I press the right mouse button, I get a new "page" below the previous ones and the scrollbar appears. After that the map stops loading new tiles.

Is that related somehow?

**Comment by sothawo** [comment]
yes, that's the same problem, it really is a nuisance; the code to disbale the contextmenu on the map (not the markers for example) which I have still works, if the page is viewed with a normal browser. It's the WebView that must have changed something.
I think it should be possible to deactivate the whole contextmenu stuff like @myrage2000 proposed, and this could be done by adding a correspondig setting to the `MapView` class.

I'll add this to my todo's for the next days.

Although I'd prefer to get it working like it used to be.

**Comment by sothawo** [comment]
I found the regression; some error on my side in the last changes. I have it fixed locally, will release the fixed versions today or tomorrow

**Comment by sothawo** [comment]
fixed in 2.7.3 and 1.26.3
