### ISSUE TITLE
Drawing a polygon on a WMS view

### ISSUE THREAD

**Issue by lgoltz** [sothawo/mapjfx#54]
Tested with version:
 * mapfx-demo: 1.21.0
 *  Java: Oracle JRE 1.8.0_131
 *  MVN 3.6.0

In the Controller of the mapfx-demo we changed (same WMS as in #25)
```
-    private WMSParam wmsParamWFPAdminBoundaries = new WMSParam()
-            .setUrl("http://geonode.wfp.org:80/geoserver/ows")
-            .addParam("layers", "geonode:admin_2_gaul_2015");
+    private WMSParam wmsParamWFPAdminBoundaries = new WMSParam().setUrl("http://ows.terrestris.de/osm/service?").addParam("layers", "OSM-WMS");
```

and started the demo with `mvn clean package && (cd target/mapjfx-demo && ./bin/mapjfx-demo)`:
* Open `map style`
* Select 'WMS World Food Programme admin boundaries' 
  * Map is shown
* Open `tracks and polygons`
* Enable `magenta track` 
  * map focus on track
  * track is **not** visible
* Open `map style`
* Select 'OSM' 
  * track is visible

**Comment by sothawo** [comment]
simple bug; I forgot to add the layer with the features (which contains the coordinatelines) to the WMS layergroup

**Comment by lgoltz** [comment]
Thank you for your promt reply! Can you estimate when you find the time to fix this and to create a new release?

**Comment by sothawo** [comment]
I think I will be able to do this this evening or tomorrow evening

**Comment by sothawo** [comment]
https://www.sothawo.com/2019/05/mapjfx-2-7-1-and-1-26-1-with-fixes-for-wms-servers/
