### ISSUE TITLE
JavaScript map interaction

### ISSUE THREAD

**Issue by InsanusMokrassar** [sothawo/mapjfx#57]
Is there some way to interact with the map directly? I have found a few fields in the `WebView` class which could be useful for me, but they are private. I am about the field `WebEngine webEngine` and `JSObject jsMapView`. For now I need to add the primitives onto the map, but I can not find any way to do it.

**Comment by InsanusMokrassar** [comment]
I have found only one way to do it: getting from childrens of `MapView` some instance of `WebView` and using this, but it is not better way to correctly interact with it

**Comment by sothawo** [comment]
`MapView` is a JavFX component that display a map and for the user it only has the Java interface. That `MapView` uses a `WebView` and `WebEngine` is an implementation detail which is hidden from the user and I think the internals should not be leaked to the outside.
As for the `jsMapView` field: This is a `JSObject` that refers to the custom Javascript object that exists in the browser. Accessing this from Java to have additional functionality only makes sense if the Javascript object itself is modified accordingly. I don't think I will lossen the access to these objects.

If you need some functionality added to the map this should be done via the Java interface, if you need something that is not existent you are welcome to create an issue for this missing feature or if you forked this repo and have a modification you might to contribute, a PR is welcome.
