### ISSUE TITLE
1.x series org.openjfx dependency

### ISSUE THREAD

**Issue by trixon** [sothawo/mapjfx#61]
Was this addition intentional in the 1.x series?
https://github.com/sothawo/mapjfx/commit/a6f1cf49eff2669b8302b814e55d0e99d5fb7e63#diff-600376dffeb79835ede4a0b285078036R53

>         <dependency>
>             <groupId>org.openjfx</groupId>
>             <artifactId>javafx-web</artifactId>
>             <version>${openjfx.version}</version>
>         </dependency>
>

**Comment by sothawo** [comment]
Surely not. Thanks for noticing.

When working on #60 I changed the test libraries to assertj and did some version updates, but in the 2.x based branch; when merging the relevant changes into 1.x I messed up the pom.xml.

Fixed and released in 1.27.1, should be on maven central soon
