### ISSUE TITLE
Restricting MapView's zoom to a range & navigation to a (mutable) border.

### ISSUE THREAD

**Issue by JulianBroudy** [sothawo/mapjfx#62]
Setting the `Configuration` option `interactive` to false locks the map. Or what do you mean with lock? As for the restriction, this could be implemented by setting a _bounding extent_ but there are open questions: what if let's say the map is zoomed out to the maximum allowed extend, and then the window size is enlarged. At the moment enlarging the window increases the visible area, for a bounded extent would this mean to zoom in? Can you please create a new issue for this where this can be discussed?

_Originally posted by @sothawo in https://github.com/sothawo/mapjfx/issues/58#issuecomment-528079762_

**Comment by JulianBroudy** [comment]
> Or what do you mean with lock? 

By lock I mean:
User able to zoom-in, zoom-out as long as the next zoom-out level won't expose (show) any parts of the map that are not inside the borders.
User able (if not zoomed-out to maximum) to move the map around. When it is moved in a way that (if unrestricted) would show any parts of the map that are not inside the borders, the map won't show it. I'm visualizing it as a "bounce" effect between the map's imaginary border and the actual bounding box of the mapView (GUI wise).

> what if let's say the map is zoomed out to the maximum allowed extent, and then the window size is enlarged. At the moment enlarging the window increases the visible area, for a bounded extent **would this mean to zoom in?**

Currently, my program doesn't have the option to maximize. So this didn't initially occur to me. But that's a very valid point. I would say, ideally, it should do exactly what you said.

**Comment by JulianBroudy** [comment]
I'll stay tuned.
Thank you.

**Comment by sothawo** [comment]
OL 6 is released (https://github.com/openlayers/openlayers/releases/tag/v6.0.0) I will try this out , might have time this weekend

**Comment by JulianBroudy** [comment]
Hey there, is there an option to "bring to front" a Marker instead of removing the one I want in front and re-adding it?

**Comment by sothawo** [comment]
No. Markers are added as `<img>` to a `<div>` in the order they are added, and an `overlay` is added to the OpenLayers map. A _bring to front_ would have to remove the overlay and the `<img>` tag and readd it, there's no other way to change this internally.

So that's basically the same that you would achieve with a remove/add call from your program.

**Comment by JulianBroudy** [comment]
> No. Markers are added as `<img>` to a `<div>` in the order they are added, and an `overlay` is added to the OpenLayers map. A _bring to front_ would have to remove the overlay and the `<img>` tag and readd it, there's no other way to change this internally.
> 
> So that's basically the same that you would achieve with a remove/add call from your program.

Understood, thank you.

**Comment by sothawo** [comment]
good news: OpenLayers 6.0.1 can constrain the extent, so that it is not possible anymore to scroll or pan outside a given extent.
I will implement this this weekend in mapjfx

**Comment by JulianBroudy** [comment]
That's awesome, looking forward to it.

Side question:
Can you think of a way to easily control when MapView's animations are executed?
For instance: 
- clicking map twice (to move marker) before the first click's animation is done OR
- programmatically changing the MapView's extent twice without providing enough time for the first animation to finish results in this: 
![image](https://user-images.githubusercontent.com/46682375/66661231-51c5cd80-ec4f-11e9-8dbb-140ea6ad3ab8.png)
A status getter (RUNNING, NOT RUNNING) for MapView's animation would be nice if possible.

**Comment by sothawo** [comment]
Implemented in the current version.

about the animation: No easy solution I can think of.

And I don't have much time in the next week(s); got quite some work to do as Spring Data Elasticsearch project lead (besides my normal job)

**Comment by JulianBroudy** [comment]
> Implemented in the current version.

I'm sorry to bother you yet again.
Is this available in version 1.27.1?
As you can recall I opt to use this version with Java 8 since others didn't work as expected.

Thanx again.

**Comment by sothawo** [comment]
that was implemented in 1.29.0 (1.29.1 is the latest Java 8 version now)
