### ISSUE TITLE
Setting offlineCache to not active, does not take effect immediately

### ISSUE THREAD

**Issue by vewert** [sothawo/mapjfx#76]
In my application, I'd like the Offline Caching to be user configurable. Currently, when the user selects to turn off caching, I call: `offlineCache.setActive(false);`
I noticed that after doing this, the maps are still be cached. 

When I restart the application, however, with `offlineCache.setActive(false);` it doesn't cache the maps anymore. I also noticed that if I start with `offlineCache.setActive(false);` and the turn on caching with `offlineCache.setActive(true);`, it does seem to take effect immediately and file are cached.

Is this by design, or am misunderstand how this works, and/or doing something wrong.

As always thanks for your continued support of this great project.

**Comment by sothawo** [comment]
This behaviour somes from the fact, that mapjfx basically is an embedded browser (JavaFX WebView) with a lot of custom Javascript.

This browers itself does some caching which cannot be configured, that's just the normal browser behaviour. This internal cache is used by the browser as long as the application is running. When the application is closed, this internal cache is deleted.

mapjx offline cache is a mechanism, where the data requested from the browser is stored in the cache directory - the browser will itself again cache this data in it's internal cache.

You can see this internal caching when you do not enable the mapjfx offline cache and zoom out/in or move around, you will notice that tiles that have been loaded are not reloaded anymore.

So this behaviour comes from the underlying techniques used.
