### ISSUE TITLE
Rotating map markers

### ISSUE THREAD

**Issue by fanatykos** [sothawo/mapjfx#80]
Rotating map markers with the ability to edit the rotation angle of existing markers.

**Comment by sothawo** [comment]
implemented and released: 
https://www.sothawo.com/2020/04/mapjfx-1-32-0-and-2-14-0-adds-the-ability-to-rotate-markers-and-labels/

**Comment by fanatykos** [comment]
Hi Peter,
What can I say?
Perfect Job!
Thanks a lot!

Greetings

pon., 6 kwi 2020 o 13:07 Peter-Josef Meisch <notifications@github.com>
napisał(a):
