### ISSUE TITLE
Mapview scaling issue on Windows when not using 100% display scaling

### ISSUE THREAD

**Issue by vewert** [sothawo/mapjfx#81]
I was testing my application on various computers and found a strange issue. Inside the mapview, the map image was only partially filling the view, but markers were behaving as if the map filled the whole view; causing strange behavior when the map is panned and zoomed. It turns out, that the computer (Windows 10) I was using, was set to have its display scale set to 125%. If I switched it to 100%, the problem went away.

I was able to reproduce this problem, using your example app and have attached a screen shot:

![mapjfx-screenshot](https://user-images.githubusercontent.com/38388418/79600326-d6305780-809b-11ea-9aef-a30bf597d600.png)

I did some investigation and found there is jvm arg, that controls allowing hidpi; setting it to false seems to fix the problem (`-Dprism.allowhidpi=false`). This seems like usable work-around, but it effectively turns off hidpi for the entire application, which may not be ideal.

I did some further investigation and found the following bug against jdk/javafx: https://bugs.openjdk.java.net/browse/JDK-8234471

This looks similar, but I'm not sure if you are using a canvas tag or not.

I don't know if this is something you can fix or not, but thought I should log it for your reference and/or in case anyone else ran into this issue. Let me know if you need any further information.

Thanks again for developing such a great mapping utility.

**Comment by sothawo** [comment]
This is probably the same as #36 and the same problem described in https://www.sothawo.com/2018/02/mapjfx-problems/#comment-999.

I put this in a new post: https://www.sothawo.com/2020/04/mapjfx-display-problems-update/, but I'm afraid that without high resolution hardware I cannot investigate further into this

**Comment by Abu-Abdullah** [comment]
i can confirm this as well. and the workaround works as well.

the good news, the bug highlited by @vewert is solved in jfx 16-ea+1 version and it works fine now without any issue

**Comment by Abu-Abdullah** [comment]
it might be good to raise the dependency to this version as it is compatible with LTS 11.

this is a core issue in Windows and my laptop is very old and does not seem to have anything special about the screen, hence im expecting most people using windows will suffer this. so i would recommend to raise the dependecy to 16-ea+1 even though it is not beta phases.

**Comment by sothawo** [comment]
thanks for this information; I don't think I'll update to 16 yet but stay on 11 LTS with master until the next LTS is out. I will check if I will get out a new branch/version for 16

**Comment by Abu-Abdullah** [comment]
it seems i didn't put it correctly. i meant to raise the dependecy of jfx to 16 not the jdk. jfx 16 is compatible with LTS jdk 11

**Comment by vewert** [comment]
@Abu-Abdullah, thanks for the update, I'm just wondering, did you try JavaFX15 to see if that resolves the issue as well? According to the bug [JDK-8234471](https://bugs.openjdk.java.net/browse/JDK-8234471), it looks like it might have been fixed in 15.

**Comment by sothawo** [comment]
sure. But if I raise the dependency to javafx16 that means that everyone using mapjfx will have jfx16 even on system where this is no issue.

**Comment by sothawo** [comment]
I just tried this on a virtual machine and could reproduce it with jfx11. The problem did not appear with 15-ea+8 or 16-ea-1.
So [JDK-8234471](https://bugs.openjdk.java.net/browse/JDK-8234471) seems to have fixed this.
No need to update mapjfx from jfx11, all you need is add the corresponding dependency to javafx-web in the application using mapjfx. I'll write a short post about this.

**Comment by sothawo** [comment]
can you please try to use the updated dependency (https://www.sothawo.com/2020/09/mapjfx-display-problem-on-windows-10-seems-solved/) and check if this solves the problem?

**Comment by vewert** [comment]
I did a quick test of my application, using jfx 15-ea+8, and indeed the problem looks to be solved! (Note: was still using jdk 11 for my test).

As a side note, I set the JavaFX dependency using Gradle and the [javafx-gradle-plugin](https://github.com/openjfx/javafx-gradle-plugin) as follows:

```
javafx {
  version = "15-ea+8"
  modules("javafx.controls", "javafx.fxml", "javafx.media", "javafx.graphics", "javafx.web")
}
```

**Comment by Abu-Abdullah** [comment]
yes it works with jfx 15 for me as well. i guess we can have different dependency version for windows e.g.
```
<dependency>
	<groupId>org.openjfx</groupId>
	<artifactId>javafx-web</artifactId>
	<version>15-ea+8</version>
	<classifier>win</classifier>
</dependency>
```
