### ISSUE TITLE
map pointer event not triggered when mouse moves over a Marker

### ISSUE THREAD

**Issue by vewert** [sothawo/mapjfx#82]
I have a Label, below my map, which gets updated with the coordinates, as the user moves the mouse around the map (similar to the test application). When the mouse is moved over a Marker, however, the location no longer updates. It seems like the `MapViewEvent.MAP_POINTER_EVENT` doesn't get triggered when the mouse is over a Marker. Once the mouse pointer, moves away from the Marker, all works fine again.

I'm not sure if this is the same as [Issue 78](https://github.com/sothawo/mapjfx/issues/78); but if it is, I am still seeing the problem. Note: I am using version 2.14.0

Thanks again for this excellent product.

**Comment by sothawo** [comment]
fixed in 1.32.1 and 2.14.1

**Comment by vewert** [comment]
Wow, that was fast! Thank-you you so much for your awesome support!
