### ISSUE TITLE
Draw rectangle by mouse press and drag when toggle button is selected 

### ISSUE THREAD

**Issue by lgoltz** [sothawo/mapjfx#86]
In #21 the alternative with pressed ctrl-/cmd-command was implemented. 

The solution with the toggle button is not implemented as far as we see. We try to implement a rectangle selection with a toggle button:
1. Click the toggle button
1. Press the left mouse button
1. During mouse move the rectangle is drawn in the map 
1. Release the left mouse button
1. Rectangle is drawn in the map until the user clicks the toggle button, or restarts at 2.

Currently we are not able to catch the mouse pressed/mouse released events. Is it possible to implement this without any changes in mapjfx? 
Or is it possible to enhance mapjfx by a starting point to implement this feature?

**Comment by sothawo** [comment]
No. currently the Openlayers _singleclick_ event is passed out as a `MAP_CLICKED` event, that is the combination of press and release. 

Looking at the [OpenLayers API](https://openlayers.org/en/latest/apidoc/module-ol_Map-Map.html) there are no distinct events fired for press and release, so I cannot pass them out.

So you could start and finish the rectangle draw with a single click each - not a really nice solution I have to admit.
