### ISSUE TITLE
Problem with marker rotation

### ISSUE THREAD

**Issue by mimenz** [sothawo/mapjfx#92]
Hi there,
first of all: thanks for this great lib!

I tried to implement a rotation on some of the markers on the map. The goal is a steady rotation using a constant angle - in contrast to the animation used in the demo.

But it seems that the rotation is gone whenever the map changes (zoom, move, etc). Which happens at once because I'm changing the extent after startup.
So currently it is not possible to set a rotation angle **_once_** on a marker and have it persistent? Or am I missing something?

Thanks, bye,
Michael

**Comment by sothawo** [comment]
Yes, panning/zooming the map draws the marker in it's original position, although the Java marker object has the rotation information.
Definitely a bug.

**Comment by sothawo** [comment]
fixed in 1.33.1 and 2.15.1
