### ISSUE TITLE
Marker rotation

### ISSUE THREAD

**Issue by mimenz** [sothawo/mapjfx#93]
Thanks for the quick patch of bug #92!

Another little issue:
added a marker with rotation angle set - if I remove the marker from the map an reinsert the marker again (*), then the rotation is lost again.

(*) I do this to ensure a "marker-to-front" behaviour.

Currently this workaround helps: remove the marker from the map, set rotation to 0, add it to the map again and set the previous angle again.

**Comment by sothawo** [comment]
fixed in 2.15.2 and 1.33.2, should be in maven central soon
