### ISSUE TITLE
When setting the WINDOWS Screen zoom to 150 % The map does not fill the whole app view

### ISSUE THREAD

**Issue by joehei** [sothawo/mapjfx#94]
Hi, 
at first create work I really love it.

I have a 4K screen which I am running on WINDOWS with a 150% zoom factor. 

![image](https://user-images.githubusercontent.com/46645618/97348749-e1f0a800-188e-11eb-92b1-5f193957cc6e.png)

When I set the zoom factor to 100% the app looks correct.

![image](https://user-images.githubusercontent.com/46645618/97348906-18c6be00-188f-11eb-8b78-28b1d1874a74.png)

Is this a WINDOWS problem or an program issue.

**Comment by sothawo** [comment]
please see the solution at the end of the discussion in issue #81. You need to use Java 15

**Comment by joehei** [comment]
I do, but I still have the problem.

08:28:30.017 [JavaFX Application Thread] INFO com.sothawo.mapjfxdemo.DemoApp - starting DemoApp
08:28:30.019 [JavaFX Application Thread] DEBUG com.sothawo.mapjfxdemo.DemoApp - loading fxml file /fxml/DemoApp.fxml
08:28:30.411 [JavaFX Application Thread] DEBUG com.sothawo.mapjfxdemo.Controller - map type toggled to RadioButton[id=radioMsOSM, styleClass=radio-button]'OSM'
08:28:30.459 [JavaFX Application Thread] DEBUG com.sothawo.mapjfx.MapView - initializing...
08:28:30.468 [JavaFX Application Thread] DEBUG com.sothawo.mapjfx.MapView - Configuration{projection=WEB_MERCATOR, interactive=true, showZoomControls=false}
08:28:30.468 [JavaFX Application Thread] DEBUG com.sothawo.mapjfx.MapView - loading from jar:file:///C:/Users/jh/.m2/repository/com/sothawo/mapjfx/2.15.2/mapjfx-2.15.2.jar!/mapview.html
08:28:31.996 [JavaFX Application Thread] DEBUG com.sothawo.mapjfx.MapView - Java Version:   15+36
08:28:31.996 [JavaFX Application Thread] DEBUG com.sothawo.mapjfx.MapView - JavaFX Version: 15.0.1+1
08:28:31.996 [JavaFX Application Thread] DEBUG com.sothawo.mapjfx.MapView - OS:             Windows 10, 10.0, amd64
08:28:31.996 [JavaFX Application Thread] DEBUG com.sothawo.mapjfx.MapView - User Agent:     Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/606.1 (KHTML, like Gecko) JavaFX/11 Safari/606.1
08:28:31.997 [JavaFX Application Thread] DEBUG com.sothawo.mapjfx.MapView - load html into WebEngine

**Comment by sothawo** [comment]
Can't reproduce this with 15.01.

But in the log output you show, there is a JavaFX/11 user agent, it seems that somehow in your setup not all of the JavaFX components are loaded from version 15. The same output from my setup:

> 06:54:50.653 DEBUG [JavaFX Application Thread] com.sothawo.mapjfx.MapView - Java Version:   15.0.1+9
> 06:54:50.654 DEBUG [JavaFX Application Thread] com.sothawo.mapjfx.MapView - JavaFX Version: 15.0.1+1
> 06:54:50.654 DEBUG [JavaFX Application Thread] com.sothawo.mapjfx.MapView - OS:             Windows 10, 10.0, amd64
> 06:54:50.655 DEBUG [JavaFX Application Thread] com.sothawo.mapjfx.MapView - User Agent:     Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/610.1 (KHTML, like Gecko) **JavaFX/15** Safari/6
10.1

**Comment by joehei** [comment]
You are right, there was a dependency which is comming from your maven dependency. I had to exclude the web component.

   <dependency>
      <groupId>com.sothawo</groupId>
      <artifactId>mapjfx</artifactId>
      <version>${mapjfx.version}</version>
      <exclusions>
        <exclusion>
          <groupId>org.openjfx</groupId>
          <artifactId>javafx-web</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

It would be an option if you use the latest JavaFX version, it is compatiple with Java 11.

Now everything is fine the issue can be closed. Many thanks for your efforts.
