### ISSUE TITLE
mapjfx doesn't work with javafx 12 or higher on macOS with Silicon chip

### ISSUE THREAD

**Issue by vewert** [sothawo/mapjfx#95]
Note: This is more of a _heads up_ than a bug.

I tried running my application on macOS Big Sur, with the new Apple Silicon (ARM) chip, but the app crashed on start up, and gave and gave an error report. I'm not very good at deciphering Apple's error reports but I did see the following:

`Thread 0 Crashed:: Dispatch queue: com.apple.main-threadThread 0 Crashed:: Dispatch queue: com.apple.main-thread0   libjfxwebkit.dylib             0x00000001343dbfd4 void std::__1::__call_once_proxy<std::__1::tuple<Gigacage::ensureGigacage()::$_0&&> >(void*) + 804`

With the key part being `libjfxwebkit.dylib`. This pointed me in the direction that it could have something to do with mapjfx, so, in my start up code, I removed the calls to display the map, and I could then start my application successfully.

I next tried running the mapjfx demo application, and to my surprise it worked! I then realized that the demo application is using JavaFX11, and I was using JavaFX15. When I switched my application to use JavaFX11, it started up, with mapping.

I tried other versions of JavaFX (12, 13 and 14), but none of them worked, so its seems something must have changed from 11 to 12 (probably with webkit), that causes it not to work with the macOS silicon chip.

I realize that mapjfx only officially supports JavaFX11 (I think), but I think this is something to look out for.

For me, my current work around will be to do a separate build to support macOS on Silicon, that uses JavaFX 11.

**Comment by sothawo** [comment]
thanks for pointing this out.
mapjfx uses the WebView of JavaFX which is using a Webkit based browser from JavaFX. And Webkit uses native code. So all we can do here is wait for versions of JavaFX that are compatible with the different Java versions.

**Comment by sothawo** [comment]
closing this issue as this is nothing where I can do something about it.
