### ISSUE TITLE
Not loading with current OpenJFX 8

### ISSUE THREAD

**Issue by mimenz** [sothawo/mapjfx#96]
Hi,
again thank you for your great and very helpful lib - and your fast response time to issues!

I saw that you're testing the lib against the Oracle JDK 8, currently 251?

In the commercial environment I wanted to use the OpenJDK 8 along with the OpenJFX 8.
But after the update 8_202 they changed/patched the WebView component. Since then MapJFX won't initialize any more. 
So my current workaround is to stick to the Oracle JDK 8_202(!) which is the latest free JDK from Oracle. But now of course there are no more security patches...

Did you test against current OpenJDK/JFX releases of Java 8? Can you dig down to the problem and the cause? I have no clue what is happening.

Thanks a lot, have a nice day,
Michael

**Comment by PeregrineFalcon** [comment]
I am having similar issues with WebView and OpenJDK 8.

**Comment by sothawo** [comment]
I use the Oracle JDK for developing and testing because it has JavaFX included. I don't find OpenJFX in version 8. How do you set this up?

**Comment by mimenz** [comment]
There are several possibilities, I tried these two.

Either you take the OpenJDK/JFX-Builds from the ojdkbuild project on GitHub:
https://github.com/ojdkbuild/ojdkbuild/releases/tag/java-1.8.0-openjdk-1.8.0.275-1.b01-x86
Just unzip the openjfx-8.0.202-1.b15.ojdkbuild.windows.x86.zip to the same target folder where you extracted the java-1.8.0-openjdk-1.8.0.275-1.b01.ojdkbuild.windows.x86.zip

Or you use the JDK from Azul named ZuluFX (which has bundled both the JDK and JFX):
https://www.azul.com/downloads/zulu-community/?version=java-8-lts&os=windows&package=jdk-fx

Thanks a lot!

**Comment by sothawo** [comment]
I just downloaded the Azul version:
```
$ java -version
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (Zulu 8.50.0.53-CA-win64) (build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (Zulu 8.50.0.53-CA-win64) (build 25.275-b01, mixed mode)
```

and then running the test application from the mapjfx project with
```
mvn test exec:java -Dexec.mainClass="com.sothawo.mapjfx.TestApp" -Dexec.classpathScope=test
```
works like it should.

Using the mapjfx-demo aplication:
```
mvn package && (cd target/mapjfx-demo && ./bin/mapjfx-demo)
```
is also running without problems.

Using Windows10, Version 2004 (Build 19041.508)

**Comment by mimenz** [comment]
Ok, I didn't try the demo, it happens in my application. And currently I have to use the 32bit JVM.
So I will investigate further on that bug. I hope that I can narrow it down...

**Comment by mimenz** [comment]
After your post I tried the ZuluFX 8_275 64bit - and MapJFX within my application works!!
So the bug only appears in the 32bit version of current OpenJDK 8 implementations...
(Too bad it still have to use it!)

**Comment by sothawo** [comment]
This definitely seems to be a problem of the JavaFX implementation (WebView uses WebKit which has native components).
So I'm closing this issue here.
